package com.example.gameledger

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import android.widget.Toast
import com.example.gameledger.databinding.ActivityInsertBinding
import com.google.firebase.database.DataSnapshot
import com.google.firebase.database.DatabaseError
import com.google.firebase.database.ValueEventListener
import com.google.firebase.database.ktx.database
import com.google.firebase.ktx.Firebase

class InsertActivity : AppCompatActivity() {
    lateinit var binding:ActivityInsertBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityInsertBinding.inflate(layoutInflater)
        setContentView(binding.root)

        inputData()
    }

    fun inputData(){
        val database = Firebase.database
        val user = database.getReference("users").child("userid")
        user.addValueEventListener(object : ValueEventListener {
            override fun onDataChange(dataSnapshot: DataSnapshot) {
                var type:Int = 0
                binding.expendRadioButton.setOnClickListener {
                    type = 0
                    Toast.makeText(this@InsertActivity, "지출을 입력합니다.", Toast.LENGTH_SHORT).show()
                }
                binding.incomeRadioButton.setOnClickListener {
                    type = 1
                    Toast.makeText(this@InsertActivity, "수입을 입력합니다.", Toast.LENGTH_SHORT).show()
                }
                binding.cancelButton.setOnClickListener {
                    var intent = Intent(this@InsertActivity, MainActivity::class.java)
                    startActivity(intent)
                }
                binding.inputButton.setOnClickListener {
                    var date = binding.dateInputText.text.toString()
                    var category = binding.categoryInputText.text.toString()
                    var title = binding.titleInputText.text.toString()
                    var value = binding.valueInputText.text.toString()
                    var trans = Transactions(type, category, date,title, value)

                    val newRef = user.child("transactions").push() // This generates a unique key for the new data
                    newRef.setValue(trans)
                        .addOnSuccessListener {
                            // Data successfully saved
                            // newRef.key contains the unique key generated by push()
                            Log.d("SUCCESS", "Data pushed to Firebase with key: ${newRef.key}")
                        }
                        .addOnFailureListener { e ->
                            // Failed to save data
                            Log.e("FAIL", "Error pushing data to Firebase")
                        }

                    var intent = Intent(this@InsertActivity, MainActivity::class.java)
                    startActivity(intent)
                }
            }

            override fun onCancelled(databaseError: DatabaseError) {
                Log.e("FAIL", "Error fetching data")
            }
        })
    }


}